# GitHub Actions Workflow for Running Tests & Building the Project

name: Tests

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: ./docker-compose.yml

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Sync environment variables
        run: cp .env.dist .env && export $(grep -v '^#' .env | xargs)

      - name: Start Docker services
        run: docker compose up -d # Updated to modern command

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn build

      - name: Check Docker services
        run: docker compose ps && docker compose logs

      - name: Run tests with coverage (using npm-run-all2)
        run: npx npm-run-all2 -p test test:cov

      - name: Store test coverage results
        if: success()
        run: mv coverage/lcov.info coverage.lcov # Ensures consistent coverage file location